#!/usr/bin/env python3
"""Regenerate flick_db_embedded.cpp/.hpp (the warped-replay stroke DB compiled
into the binary) from a flick_trajectories.json.

The input flick_trajectories.json is produced by the SEPARATE companion repo
`mouse-bot-detector` (scripts/export_flick_db.py); it is not part of this repo.
This script only turns that json into the embedded C++ source.

Usage:
    python gen_flick_db_embedded.py [path/to/flick_trajectories.json]
Writes flick_db_embedded.cpp and flick_db_embedded.hpp next to this script.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
src = sys.argv[1] if len(sys.argv) > 1 else "flick_trajectories.json"

d = json.load(open(src))
# Compact precision (4dp coords, 1dp time) - verified not to affect detection.
for t in d["traj"]:
    t["s"] = [[round(a, 4), round(b, 4)] for a, b in t["s"]]
    t["t"] = [round(x, 1) for x in t["t"]]
    t["d"] = round(t["d"], 2)
compact = json.dumps(d, separators=(",", ":"))
assert ')FLICKDB"' not in compact, "raw-string delimiter collision in data"

with open(os.path.join(HERE, "flick_db_embedded.hpp"), "w") as f:
    f.write("#pragma once\n"
            "// Auto-generated by gen_flick_db_embedded.py from flick_trajectories.json\n"
            "// (json produced by the separate mouse-bot-detector repo). The warped-replay\n"
            "// stroke DB, compiled into the binary so no external file is needed.\n"
            "extern const char flick_db_embedded_json[];\n"
            "extern const unsigned long flick_db_embedded_size;\n")
with open(os.path.join(HERE, "flick_db_embedded.cpp"), "w") as f:
    f.write('#include "flick_db_embedded.hpp"\n')
    f.write('const char flick_db_embedded_json[] = R"FLICKDB(' + compact + ')FLICKDB";\n')
    f.write('const unsigned long flick_db_embedded_size = sizeof(flick_db_embedded_json) - 1;\n')

print(f"wrote flick_db_embedded.cpp ({len(compact)/1024:.0f} KB) + .hpp from {src}")
